import { Router } from 'express';
import authRoutes from './auth.routes';
import aiRoutes from './ai.routes';
import usersRoutes from './users.routes';
import studentsRoutes from './students.routes';
import teachersRoutes from './teachers.routes';
import classesRoutes from './classes.routes';
import schoolYearsRoutes from './school-years.routes';
import semestersRoutes from './semesters.routes';
import gradesRoutes from './grades.routes';
import attendanceRoutes from './attendance.routes';
import timetableRoutes from './timetable.routes';
import notificationsRoutes from './notifications.routes';
import permissionsRoutes from './permissions.routes';
import activitiesRoutes from './activities.routes';
import studentSelfRoutes from './student-self.routes';
import securityLogsRoutes from './security-logs.routes';
import rulesRoutes from './rules.routes';
import roomsRoutes from './rooms.routes';
import yearTransitionRoutes from './year-transition.routes';
import promotionEvaluationRoutes from './promotion-evaluation.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/ai', aiRoutes);
router.use('/users', usersRoutes);
router.use('/students', studentsRoutes);
router.use('/teachers', teachersRoutes);
router.use('/classes', classesRoutes);
router.use('/school-years', schoolYearsRoutes);
router.use('/semesters', semestersRoutes);
router.use('/grades', gradesRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/timetables', timetableRoutes);
router.use('/student-self', studentSelfRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/activities', activitiesRoutes);
router.use('/security-logs', securityLogsRoutes);
router.use('/rules', rulesRoutes);
router.use('/rooms', roomsRoutes);
router.use('/year-transition', yearTransitionRoutes);
router.use('/year-results', promotionEvaluationRoutes);

export default router;
